export const products = [
  {
    id: 1,
    name: "T-SHIRT WITH TAPE DETAILS",
    image: "/products/shirt.svg",
    rating: 4,
    price: 120,
  },
  {
    id: 2,
    name: "SLEEVE STRIPED T-SHIRT",
    image: "/products/striped-shirt.png",
    rating: 4,
    price: 100,
  },
  {
    id: 3,
    name: "CHECKERED SHIRT",
    image: "/products/checked.png",
    rating: 4,
    price: 80,
  },
  {
    id: 4,
    name: "LOOSE FIT BERMUDA SHORTS",
    image: "/products/shorts.png",
    rating: 4,
    price: 50,
  },
  {
    id: 5,
    name: "SKINNY FIT JEANS",
    image: "/products/skinny.png",
    rating: 4,
    price: 85,
  },
  {
    id: 6,
    name: "COURAGE GRAPHIC T-SHIRT",
    image: "/products/courage.png",
    rating: 4,
    price: 145,
  },
  {
    id: 7,
    name: "VERTICAL STRIPED SHIRT",
    image: "/products/vertical.png",
    rating: 4,
    price: 125,
  },
  {
    id: 8,
    name: "T-SHIRT WITH TAPE DETAILS",
    image: "/products/shirt.svg",
    rating: 4,
    price: 120,
  },
  {
    id: 9,
    name: "SLEEVE STRIPED T-SHIRT",
    image: "/products/striped-shirt.png",
    rating: 4,
    price: 100,
  },
];
